name: Run tests

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Ensure files are formatted with black
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          black --check ./coatnet/dataloader/*.py
          black --check ./coatnet/models/*.py
          black --check ./coatnet/utils.py
          black --check tests.py
          black --check sanity_test.py
          black --check train.py
